### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by z77517615**
老師,我是鄭惠娟
測試網址http://52.194.56.157:3000/

### CODE REVIEW

**Comment by cwpeng** [comment]
1. Your layout exceed the width of screen in the small to middle screen size. (<1200px)
2. Your code will load pages infinitely even if we have reached the last page of data.

Fix issues and leave comment for me to review again.

未命名-4

**Comment by z77517615** [comment]
老師已更新,增加CSS排版及js判斷式

**Comment by cwpeng** [comment]
Layout is still broken.

未命名-8

**Comment by z77517615** [comment]
已更改input位置，麻煩老師review

**Comment by cwpeng** [comment]
It's not about position of input. The point is your layout exceed the width of screen. Feel free to talk/message to me if you cannot get my point.

**Comment by z77517615** [comment]
老師,更改圖片background部分(我想你應該是指版面超過螢幕寬度需要滑動的事......?)麻煩你再review

**Review by cwpeng — APPROVED** [review]
OK. Done.

**Pull request merged**
